# Generated by Django 2.2.10 on 2020-02-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('visited', models.BooleanField(default=False)),
                ('power', models.IntegerField(default=0)),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Continent')),
            ],
        ),
    ]
